name: Keep Supabase Alive

on:
  workflow_dispatch:  # 加这一行，允许手动触发
  schedule:
    - cron: '0 0 */5 * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl https://cqhmzlcmgtwxomubdzsv.supabase.co/rest/v1/
